# Generated by Django 5.2.5 on 2025-08-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=200)),
                ('itemPrice', models.IntegerField()),
                ('itemImage', models.ImageField(upload_to='items/')),
            ],
        ),
    ]
